In [2]:
from numpy import *

In [3]:
a=array([[17,17,5],[21,18,21],[2,2,19]])
b=array([[15],[0],[24]])
dot(a,b)#use "dot" to multiply

array([[375],
       [819],
       [486]])

In [4]:
dot(a,b)% 26#amazing!!!  

array([[11],
       [13],
       [18]], dtype=int32)

In [5]:
b2=array([[12],[14],[17]])
b3=array([[4],[12],[14]])
b4=array([[13],[4],[24]])
dot(a,b2)% 26

array([[ 7],
       [ 3],
       [11]], dtype=int32)

In [6]:
dot(a,b3)% 26

array([[ 4],
       [22],
       [12]], dtype=int32)

In [7]:
dot(a,b4)% 26

array([[19],
       [17],
       [22]], dtype=int32)

In [8]:
#the mapping sheet between letter and number
#a 0
#b 1
#c 2
#d 3
#e 4
#f 5
#g 6
#h 7
#i 8
#j 9
#k 10
#l 11
#m 12
#n 13
#o 14
#p 15
#q 16
#r 17
#s 18
#t 19
#u 20
#v 21
#w 22
#x 23
#y 24
#z 25

In [9]:
i=1
while (24*i)%26!=10:
    i+=1
i#value of b

8

In [10]:
keya=1
while (keya*8+24)%26!=2:
    keya+=1
keya

7

In [11]:
keyd=1
while (keyd*24)%26!=20:
    keyd+=1
keyd

3

In [12]:
keyc=1
while (keyc*5+17*3)%26!=16:
    keyc+=1
keyc

19

In [14]:
keyc2=19
while (keyc2*8+3*3)%26!=5:
    keyc2+=1
keyc2

19

In [15]:
a=0
for b in (1,3,5,7,9,11,15,17,19,21,23,25):
    for a in range(26):
        if (4*b+a)%26==5 and (7*b+a)%26==22:
            print(a,b)        

17 23


In [18]:
a=array([[7,8],[19,3]])
b=array([[5],[17]])
dot(a,b)%26

array([[15],
       [16]], dtype=int32)

In [27]:
xishu=array([[24,14,20],[17,15,8],[13,13,14]])
ans=array([[22],[5],[19]])
linalg.solve(xishu,ans)%26

array([[ 25.22558923],
       [  0.20538721],
       [  1.88552189]])

In [1]:
13440%26

24

In [11]:
x=1
while (24*x)%26!=12:
    x+=1
x#value of b

7